### ISSUE TITLE
Succeeding even though ssh command is failed

### ISSUE THREAD

**Issue by tbhaxor** [cross-the-world/ssh-scp-ssh-pipelines#3]
Please see this pic and you will understand my concern
![Screenshot_20201001_161829](https://user-images.githubusercontent.com/28386721/94800123-c87c4d80-0401-11eb-958f-ebf976d28df7.png)

**Comment by thuongnht** [comment]
Hi,

Thanks. I will try to fix it.
No error on pipeline despite command ran failed inside, has been already a problem which I knew.

Best regards,
Thuong.

**Comment by thebaptiste** [comment]
Same problem for me : the authentification was incorrect but the step was successful.

**Comment by tbhaxor** [comment]
@thebaptiste for now use https://github.com/appleboy/scp-action. I am using the same action in almost all of my projects

**Comment by thebaptiste** [comment]
@tbhaxor : Thanks, I know scp-action but what I like with ssh-scp-ssh-pipelines is the possibility to mix ssh and scp requests in a single step, for example : create a repository (ssh), push rpms in it (scp) then run createrepo (ssh).
But with this issue, ssh-scp-ssh-pipelines can't be used in a "CI" context... Too bad... I will probably go back to appleboy/scp-action and appleboy/ssh-action with 3 steps instead of one single.

**Comment by tbhaxor** [comment]
Yeah, if the this issue will be resolved, I will switch back to this actions in all my repos. But i gave you an instant solution :smile:
